export { MainPage } from './MainPage/MainPage'
export { NotFoundPage } from './NotFoundPage/NotFoundPage'
export { AddPlacePage } from './AddPlacePage/AddPlacePage'
export { PlacePage } from './PlacePage/PlacePage'
export { AddFactPage } from './AddFactPage/AddFactPage'
